kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mssql-data-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---

apiVersion: v1
kind: Service
metadata:
  name: mssql
  labels:
    app: mssql
spec:
  type: NodePort
  ports:
    - name: external
      port: 1433
      nodePort: 31433
  selector:
    app: mssql

---
apiVersion: v1
kind: Service
metadata:
  name: mssql-internal
  labels:
    app: mssql
spec:
  type: ClusterIP
  ports:
    - port: 1433
      name: internal
  selector:
    app: mssql
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: mssql
  labels:
    app: mssql
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: mssql
  template:
    metadata:
      labels:
        app: mssql
    spec:
      containers:
        - name: mssql
          image: microsoft/mssql-server-linux:2017-latest
          env:
            - name: MSSQL_PID
              value: Express
            - name: ACCEPT_EULA
              value: "Y"
            - name: SA_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mssql-password
                  key: password
          ports:
            - name: mssql
              containerPort: 1433
          volumeMounts:
            - name: mssql-persistent-storage
              mountPath: /var/opt/mssql
      volumes:
        - name: mssql-persistent-storage
          persistentVolumeClaim:
            claimName: mssql-data-claim
